services:
    postgres-vet-dev:
        image: postgres:15.3-alpine
        container_name: postgres-vet-dev
        # restart: always
        env_file:
            - .env.dev
        ports:
            - 5432:5432
